version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: kids
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/kids
      - CORS_ORIGINS=http://13.49.226.196,http://localhost:3000,http://127.0.0.1:3000
      - SECRET_KEY=8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92
      - GROK_API_KEY=xai-SIdr7qy50GxzLJHKdXrQ0NEQ8gD4zAacLA3ExH4Uc3mXfApAB2mPvndWSGz2FE8N50o1Q21mGT3jMBEN
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend  # 确保这个路径正确
      dockerfile: Dockerfile
    volumes:  # 添加卷映射，方便调试
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
